version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: risk-score-db
    restart: unless-stopped
    env_file:
      - .env.local      # ← берём переменные отсюда
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: risk-score-app
    restart: unless-stopped
    env_file:
      - .env.local      # те же переменные доступны внутри app
    depends_on:
      - db
    ports:
      - "3000:3000"



volumes:
  db-data:
