apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: risk-score-app
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
